/**
 * authConstant.js
 * @description :: constants used in authentication
 */
const JWT = {
  SECRET: process.env.JWT_SECRET || 'default_jwt_secret_key',
  JWT_TEMP_SECRET: process.env.JWT_TEMP_SECRET || 'default_jwt_temp_secret_key',
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET || 'default_jwt_refresh_secret_key',
  EXPIRES_IN: 30,
  OTP_EXPIRES_IN: 120,
  JWT_REFRESH_EXPIRY: '7d',
  ALGORITHM: process.env.JWT_ALGORITHM || 'HS256',
  ISSUER: process.env.JWT_ISSUER || 'gmaxepay',
  AUDIENCE: process.env.JWT_AUDIENCE || 'gmaxepay_users'
};

const USER_TYPES = {
  SUPER_ADMIN: 1,
  ADMIN: 2,
  SUB_ADMIN: 3,
  RETAILER: 4,
  MASTER_DISTRIBUTOR: 5,
  DISTRIBUTOR: 6,
  API_USER: 7,
  WHITELABEL_ADMIN: 13
};

const TYPES = {
  APPLICATION_USER: 1,
  EMPLOYEE: 2
};

const EMPLOYEE_TYPES = {
  EMPLOYEE: 8,
  SALES_MANAGER: 9,
  SALES_EXECUTIVE: 10,
  CUSTOMER_SUPPORT: 11
};

const PLATFORM = {
  SUPER_ADMIN: 1,
  ADMIN: 2,
  SUB_ADMIN: 3,
  RETAILER: 4,
  MASTER_DISTRIBUTOR: 5,
  DISTRIBUTOR: 6,
  API_USER: 7,
  EMPLOYEE: 8,
  SALES_MANAGER: 9,
  SALES_EXECUTIVE: 10,
  CUSTOMER_SUPPORT: 11
};
const USERS = {
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  10: 10,
  11: 11
};

let LOGIN_ACCESS = {
  [USER_TYPES.SUPER_ADMIN]: [PLATFORM.SUPER_ADMIN],
  [USER_TYPES.ADMIN]: [PLATFORM.ADMIN],
  [USER_TYPES.SUB_ADMIN]: [PLATFORM.SUB_ADMIN],
  [USER_TYPES.RETAILER]: [PLATFORM.RETAILER],
  [USER_TYPES.MASTER_DISTRIBUTOR]: [PLATFORM.MASTER_DISTRIBUTOR],
  [USER_TYPES.DISTRIBUTOR]: [PLATFORM.DISTRIBUTOR],
  [USER_TYPES.API_USER]: [PLATFORM.API_USER],
  [EMPLOYEE_TYPES.EMPLOYEE]: [PLATFORM.EMPLOYEE],
  [EMPLOYEE_TYPES.SALES_MANAGER]: [PLATFORM.SALES_MANAGER],
  [EMPLOYEE_TYPES.SALES_EXECUTIVE]: [PLATFORM.SALES_EXECUTIVE],
  [EMPLOYEE_TYPES.CUSTOMER_SUPPORT]: [PLATFORM.CUSTOMER_SUPPORT]
};

const MAX_LOGIN_RETRY_LIMIT = 3;
const MAX_RESEND_OTP_RETRY_LIMIT = 3;
const MAX_LOGIN_OTP_RETRY_LIMIT = 3;
const LOGIN_REACTIVE_TIME = 20;
const OTP_REACTIVE_TIME = 1;

const FORGOT_PASSWORD_WITH = {
  LINK: {
    email: true,
    sms: false
  },
  EXPIRE_TIME: 20
};

const KYC_STATUS = {
  NO_KYC: 0,
  BASIC_KYC: 1,
  FULL_KYC: 2,
  REJECTED: 4
};
const TEMPLATE_TYPE = {
  MESSAGE: 0,
  NOTIFICATION: 1,
  EMAIL: 2,
  ALERT: 3,
  WHATSAPP: 4
};

module.exports = {
  JWT,
  USER_TYPES,
  EMPLOYEE_TYPES,
  PLATFORM,
  MAX_LOGIN_RETRY_LIMIT,
  LOGIN_REACTIVE_TIME,
  FORGOT_PASSWORD_WITH,
  LOGIN_ACCESS,
  OTP_REACTIVE_TIME,
  MAX_RESEND_OTP_RETRY_LIMIT,
  MAX_LOGIN_OTP_RETRY_LIMIT,
  KYC_STATUS,
  TEMPLATE_TYPE,
  USERS,
  TYPES
};
