/**
 * authConstant.js
 * @description :: constants used in authentication
 */

// Ensure environment variables are loaded
require('dotenv').config({ path: '.env' });

const JWT = {
  get SECRET() {
    return process.env.JWT_ACCESS_SECRET;
  },
  get JWT_TEMP_SECRET() {
    return process.env.JWT_TEMP_SECRET;
  },
  get JWT_REFRESH_SECRET() {
    return process.env.JWT_REFRESH_SECRET;
  },
  EXPIRES_IN: 30, // 30 minutes for access token
  OTP_EXPIRES_IN: 180,
  JWT_REFRESH_EXPIRY: '360m', // 6 hours
  TOTAL_SESSION_MINUTES: 360, // 6 hours
  ALGORITHM: process.env.JWT_ALGORITHM || 'HS256',
  ISSUER: process.env.JWT_ISSUER || 'gmaxepay',
  AUDIENCE: process.env.JWT_AUDIENCE || 'gmaxepay_users',
  TOKEN_ENCRYPT_EXPIRY: 300,
  SIGNATURE_TOKEN_EXPIRY: process.env.SIGNATURE_TOKEN_EXPIRY || '6h'
};

const USER_TYPES = {
  SUPER_ADMIN: 1,
  ADMIN: 2,
  SUB_ADMIN: 3,
  RETAILER: 4,
  MASTER_DISTRIBUTOR: 5,
  DISTRIBUTOR: 6,
  API_USER: 7,
  WHITELABEL_ADMIN: 13
};

const TYPES = {
  APPLICATION_USER: 1,
  EMPLOYEE: 2
};

const EMPLOYEE_TYPES = {
  EMPLOYEE: 8,
  SALES_MANAGER: 9,
  SALES_EXECUTIVE: 10,
  CUSTOMER_SUPPORT: 11
};

const PLATFORM = {
  SUPER_ADMIN: 1,
  ADMIN: 2,
  SUB_ADMIN: 3,
  RETAILER: 4,
  MASTER_DISTRIBUTOR: 5,
  DISTRIBUTOR: 6,
  API_USER: 7,
  EMPLOYEE: 8,
  SALES_MANAGER: 9,
  SALES_EXECUTIVE: 10,
  CUSTOMER_SUPPORT: 11
};
const USERS = {
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  10: 10,
  11: 11
};

let LOGIN_ACCESS = {
  [USER_TYPES.SUPER_ADMIN]: [PLATFORM.SUPER_ADMIN],
  [USER_TYPES.ADMIN]: [PLATFORM.ADMIN],
  [USER_TYPES.SUB_ADMIN]: [PLATFORM.SUB_ADMIN],
  [USER_TYPES.RETAILER]: [PLATFORM.RETAILER],
  [USER_TYPES.MASTER_DISTRIBUTOR]: [PLATFORM.MASTER_DISTRIBUTOR],
  [USER_TYPES.DISTRIBUTOR]: [PLATFORM.DISTRIBUTOR],
  [USER_TYPES.API_USER]: [PLATFORM.API_USER],
  [EMPLOYEE_TYPES.EMPLOYEE]: [PLATFORM.EMPLOYEE],
  [EMPLOYEE_TYPES.SALES_MANAGER]: [PLATFORM.SALES_MANAGER],
  [EMPLOYEE_TYPES.SALES_EXECUTIVE]: [PLATFORM.SALES_EXECUTIVE],
  [EMPLOYEE_TYPES.CUSTOMER_SUPPORT]: [PLATFORM.CUSTOMER_SUPPORT]
};

const MAX_LOGIN_RETRY_LIMIT = 3; // Unified retry limit for both password and OTP attempts
const MAX_RESEND_OTP_RETRY_LIMIT = 3;
const LOGIN_LOCK_TIME = 20; // Unified lock time in minutes for both password and OTP failures

const FORGOT_PASSWORD_WITH = {
  LINK: {
    email: true,
    sms: false
  },
  EXPIRE_TIME: 20
};

const KYC_STATUS = {
  NO_KYC: 0,
  BASIC_KYC: 1,
  FULL_KYC: 2,
  REJECTED: 4
};
const TEMPLATE_TYPE = {
  MESSAGE: 0,
  NOTIFICATION: 1,
  EMAIL: 2,
  ALERT: 3,
  WHATSAPP: 4
};

module.exports = {
  JWT,
  USER_TYPES,
  EMPLOYEE_TYPES,
  PLATFORM,
  MAX_LOGIN_RETRY_LIMIT,
  LOGIN_LOCK_TIME,
  FORGOT_PASSWORD_WITH,
  LOGIN_ACCESS,
  MAX_RESEND_OTP_RETRY_LIMIT,
  KYC_STATUS,
  TEMPLATE_TYPE,
  USERS,
  TYPES
};
