const express = require('express');
const router = express.Router();
const whitelabelController = require('../../../controller/company/v1/whitelabelController');
const userController = require('../../../controller/company/v1/userContoller');
const zupayAepsController = require('../../../controller/company/v1/zupayAepsController');
const authentication = require('../../../middleware/authentication');

router.post('/list', authentication, userController.findAllUsers);
router.post('/upgradeList', authentication, userController.upgradeList);
router.post('/upgradeUser', authentication, whitelabelController.upgradeUserRole);
router.post('/degradeUser', authentication, whitelabelController.degradeUserRole);
router.post('/setMPIN', authentication, userController.setMPIN);
router.post('/resetMPIN', authentication, userController.resetMPIN);
router.post('/getProfile', authentication, userController.getUserProfile);
router.post('/reportToUserList', authentication, userController.findAllCompanyReportToUser);
router.post('/profile/:id', authentication, userController.getByUserProfile);
router.post('/kyc/complete/:id', authentication, userController.getCompleteKycData);
router.post('/kyc/revert/:id', authentication, userController.revertKycData);
router.post('/aeps-status/:id', authentication, zupayAepsController.checkOnboardingStatus);
module.exports = router;