const model = require('../../../models/index');
const dbService = require('../../../utils/dbService');
const { Op } = require('sequelize');
const { USER_TYPES } = require('../../../constants/authConstant');

/**
 * Auto-generate Good and Bad schemas for a user
 */
const autoGenerateDefaultSchemas = async (companyId, createdBy, roleType, roleName) => {
  const defaultSchemas = [
    {
      companyId,
      schemaName: 'Good Client',
      schemaType: 'good',
      createdBy,
      roleType,
      roleName,
      isDefault: true,
      isActive: true,
      description: 'Default Good Client schema'
    },
    {
      companyId,
      schemaName: 'Bad Client',
      schemaType: 'bad',
      createdBy,
      roleType,
      roleName,
      isDefault: true,
      isActive: true,
      description: 'Default Bad Client schema'
    }
  ];

  const createdSchemas = [];
  for (const schemaData of defaultSchemas) {
    const existing = await dbService.findOne(model.schema, {
      companyId,
      schemaName: schemaData.schemaName,
      roleType,
      createdBy,
      schemaType: schemaData.schemaType
    });

    if (!existing) {
      const created = await dbService.createOne(model.schema, schemaData);
      createdSchemas.push(created);
    } else {
      createdSchemas.push(existing);
    }
  }

  return createdSchemas;
};

/**
 * Create Schema
 */
const createSchema = async (req, res) => {
  try {
    let permissions = req.permission || [];
    let hasPermission = permissions.some(
      (permission) =>
        permission.dataValues.permissionId === 27 &&
        permission.dataValues.write === true
    );

    if (req.user?.userType === USER_TYPES.SUPER_ADMIN) {
      hasPermission = true;
    }

    if (!hasPermission) {
      return res.failure({ message: `User doesn't have Permission!` });
    }

    const dataToCreate = { ...(req.body || {}) };
    const companyId = req.user?.companyId;

    if (!companyId) {
      return res.failure({ message: 'Company ID is required' });
    }

    // Validate schemaType
    if (dataToCreate.schemaType && !['good', 'bad', 'custom'].includes(dataToCreate.schemaType)) {
      return res.failure({ message: 'schemaType must be "good", "bad", or "custom"' });
    }

    // Set defaults
    if (!dataToCreate.schemaType) {
      dataToCreate.schemaType = 'custom';
    }

    // Map userRole to roleType and roleName
    const roleMapping = {
      [USER_TYPES.SUPER_ADMIN]: { roleType: 1, roleName: 'AD' },
      [USER_TYPES.ADMIN]: { roleType: 2, roleName: 'WU' },
      [USER_TYPES.MASTER_DISTRIBUTOR]: { roleType: 3, roleName: 'MD' },
      [USER_TYPES.DISTRIBUTOR]: { roleType: 4, roleName: 'DI' },
      [USER_TYPES.RETAILER]: { roleType: 5, roleName: 'RE' }
    };

    const userRole = dataToCreate.roleType || req.user.userRole;
    const roleInfo = roleMapping[userRole] || { roleType: userRole, roleName: 'UNKNOWN' };

    dataToCreate.companyId = companyId;
    dataToCreate.createdBy = req.user.id;
    dataToCreate.roleType = roleInfo.roleType;
    dataToCreate.roleName = roleInfo.roleName;
    dataToCreate.isActive = dataToCreate.isActive !== false;

    // Check for duplicate schema name
    const existingSchema = await dbService.findOne(model.schema, {
      companyId,
      schemaName: dataToCreate.schemaName,
      roleType: dataToCreate.roleType,
      createdBy: dataToCreate.createdBy
    });

    if (existingSchema) {
      return res.failure({ message: 'Schema with this name already exists for this role' });
    }

    const createdSchema = await dbService.createOne(model.schema, dataToCreate);

    if (!createdSchema) {
      return res.failure({ message: 'Failed to create schema' });
    }

    return res.success({
      message: 'Schema created successfully',
      data: createdSchema
    });
  } catch (error) {
    console.error(error);
    if (error.name === 'SequelizeUniqueConstraintError') {
      return res.validationError({ message: error.errors[0].message });
    } else {
      return res.internalServerError({ message: error.message });
    }
  }
};

/**
 * Update Schema
 */
const updateSchema = async (req, res) => {
  try {
    let permissions = req.permission || [];
    let hasPermission = permissions.some(
      (permission) =>
        permission.dataValues.permissionId === 27 &&
        permission.dataValues.write === true
    );

    if (req.user?.userType === USER_TYPES.SUPER_ADMIN) {
      hasPermission = true;
    }

    if (!hasPermission) {
      return res.failure({ message: `User doesn't have Permission!` });
    }

    const schemaId = req.params.id;
    const dataToUpdate = { ...(req.body || {}) };
    const companyId = req.user?.companyId;

    const existingSchema = await dbService.findOne(model.schema, {
      id: schemaId,
      companyId
    });

    if (!existingSchema) {
      return res.failure({ message: 'Schema not found' });
    }

    // Remove fields that shouldn't be updated directly
    delete dataToUpdate.companyId;
    delete dataToUpdate.createdBy;

    dataToUpdate.updatedBy = req.user.id;

    const updatedSchema = await dbService.update(
      model.schema,
      { id: schemaId },
      dataToUpdate
    );

    return res.success({
      message: 'Schema updated successfully',
      data: updatedSchema[0]
    });
  } catch (error) {
    console.error(error);
    if (error.name === 'SequelizeUniqueConstraintError') {
      return res.validationError({ message: error.errors[0].message });
    } else {
      return res.internalServerError({ message: error.message });
    }
  }
};

/**
 * Get Schema by ID
 */
const getSchemaById = async (req, res) => {
  try {
    let permissions = req.permission || [];
    let hasPermission = permissions.some(
      (permission) =>
        permission.dataValues.permissionId === 27 &&
        permission.dataValues.read === true
    );

    if (req.user?.userType === USER_TYPES.SUPER_ADMIN) {
      hasPermission = true;
    }

    const schemaId = req.params.id;
    const companyId = req.user?.companyId;

    let query = { id: schemaId };
    if (companyId && req.user?.userType !== USER_TYPES.SUPER_ADMIN) {
      query.companyId = companyId;
    }

    const schema = await dbService.findOne(model.schema, query, {
      include: [
        { model: model.company, as: 'company' },
        { model: model.user, as: 'creator' },
        { model: model.user, as: 'assignedUser' }
      ]
    });

    if (!schema) {
      return res.recordNotFound();
    }

    return res.success({ data: schema });
  } catch (error) {
    console.error(error);
    return res.internalServerError({ message: error.message });
  }
};

/**
 * Get All Schemas
 */
const getAllSchemas = async (req, res) => {
  try {
    let permissions = req.permission || [];
    let hasPermission = permissions.some(
      (permission) =>
        permission.dataValues.permissionId === 27 &&
        permission.dataValues.read === true
    );

    if (req.user?.userType === USER_TYPES.SUPER_ADMIN) {
      hasPermission = true;
    }

    const dataToFind = req.body || {};
    const companyId = req.user?.companyId;
    let options = {};
    let query = {};

    if (dataToFind.query) {
      query = { ...query, ...dataToFind.query };
    }

    if (companyId && req.user?.userType !== USER_TYPES.SUPER_ADMIN) {
      query.companyId = companyId;
    }

    if (dataToFind.isCountOnly) {
      const count = await dbService.count(model.schema, query);
      return res.success({ data: { totalRecords: count } });
    }

    if (dataToFind.options) {
      options = dataToFind.options;
    }

    if (dataToFind.customSearch) {
      const keys = Object.keys(dataToFind.customSearch);
      const orConditions = [];

      keys.forEach((key) => {
        if (typeof dataToFind.customSearch[key] === 'number') {
          orConditions.push(
            model.sequelize.where(model.sequelize.cast(model.sequelize.col(key), 'varchar'), {
              [Op.iLike]: `%${dataToFind.customSearch[key]}%`
            })
          );
        } else {
          orConditions.push({
            [key]: {
              [Op.iLike]: `%${dataToFind.customSearch[key]}%`
            }
          });
        }
      });

      if (orConditions.length > 0) {
        query[Op.or] = orConditions;
      }
    }

    const schemas = await dbService.smspaginate(model.schema, query, options);

    if (!schemas || schemas.length === 0) {
      return res.recordNotFound();
    }

    return res.status(200).send({
      status: 'SUCCESS',
      message: 'Your request is successfully executed',
      data: schemas.data,
      total: schemas.total
    });
  } catch (error) {
    console.error(error);
    return res.internalServerError({ message: error.message });
  }
};

/**
 * Delete Schema
 */
const deleteSchema = async (req, res) => {
  try {
    let permissions = req.permission || [];
    let hasPermission = permissions.some(
      (permission) =>
        permission.dataValues.permissionId === 27 &&
        permission.dataValues.write === true
    );

    if (req.user?.userType === USER_TYPES.SUPER_ADMIN) {
      hasPermission = true;
    }

    if (!hasPermission) {
      return res.failure({ message: `User doesn't have Permission!` });
    }

    const schemaId = req.params.id;
    const companyId = req.user?.companyId;

    const existingSchema = await dbService.findOne(model.schema, {
      id: schemaId,
      companyId
    });

    if (!existingSchema) {
      return res.failure({ message: 'Schema not found' });
    }

    // Soft delete
    await dbService.update(
      model.schema,
      { id: schemaId },
      {
        isActive: false,
        isDeleted: true,
        updatedBy: req.user.id
      }
    );

    return res.success({
      message: 'Schema deleted successfully'
    });
  } catch (error) {
    console.error(error);
    return res.internalServerError({ message: error.message });
  }
};

/**
 * Assign Schema to User
 */
const assignSchemaToUser = async (req, res) => {
  try {
    let permissions = req.permission || [];
    let hasPermission = permissions.some(
      (permission) =>
        permission.dataValues.permissionId === 27 &&
        permission.dataValues.write === true
    );

    if (req.user?.userType === USER_TYPES.SUPER_ADMIN) {
      hasPermission = true;
    }

    if (!hasPermission) {
      return res.failure({ message: `User doesn't have Permission!` });
    }

    const { schemaId, userId } = req.body;
    const companyId = req.user?.companyId;

    if (!schemaId || !userId) {
      return res.failure({ message: 'Schema ID and User ID are required' });
    }

    // Verify schema exists
    const schema = await dbService.findOne(model.schema, {
      id: schemaId,
      companyId
    });

    if (!schema) {
      return res.failure({ message: 'Schema not found' });
    }

    // Verify user exists and belongs to same company
    const user = await dbService.findOne(model.user, {
      id: userId,
      companyId
    });

    if (!user) {
      return res.failure({ message: 'User not found' });
    }

    // Update user's schema
    await dbService.update(
      model.user,
      { id: userId },
      { schemaId, updatedBy: req.user.id }
    );

    // Update schema's assignedTo
    await dbService.update(
      model.schema,
      { id: schemaId },
      { assignedTo: userId, updatedBy: req.user.id }
    );

    return res.success({
      message: 'Schema assigned to user successfully'
    });
  } catch (error) {
    console.error(error);
    return res.internalServerError({ message: error.message });
  }
};

/**
 * Assign Slab to Company (Super Admin only)
 */
const assignSlabToCompany = async (req, res) => {
  try {
    if (req.user?.userType !== USER_TYPES.SUPER_ADMIN) {
      return res.failure({ message: 'Only Super Admin can assign slabs to companies' });
    }

    const { slabId, companyId } = req.body;

    if (!slabId || !companyId) {
      return res.failure({ message: 'Slab ID and Company ID are required' });
    }

    // Verify slab exists
    const slab = await dbService.findOne(model.slab, { id: slabId });
    if (!slab) {
      return res.failure({ message: 'Slab not found' });
    }

    // Verify company exists
    const company = await dbService.findOne(model.company, { id: companyId });
    if (!company) {
      return res.failure({ message: 'Company not found' });
    }

    // Get all operators to create admin commission entries
    const operators = await dbService.findAll(
      model.operator,
      {},
      { select: ['id', 'operatorName', 'operatorType'] }
    );

    // Create admin commission entries for this slab-company combination
    const commissionData = [];
    for (const operator of operators) {
      // Commission entry
      commissionData.push({
        slabId,
        companyId,
        operatorId: operator.id,
        operatorName: operator.operatorName,
        operatorType: operator.operatorType,
        commAmt: 0,
        commType: 'com',
        amtType: 'fix',
        isActive: true,
        addedBy: req.user.id
      });

      // Surcharge entry
      commissionData.push({
        slabId,
        companyId,
        operatorId: operator.id,
        operatorName: operator.operatorName,
        operatorType: operator.operatorType,
        commAmt: 0,
        commType: 'sur',
        amtType: 'fix',
        isActive: true,
        addedBy: req.user.id
      });
    }

    // Check if commissions already exist
    const existingCommissions = await dbService.findAll(model.adminCommission, {
      slabId,
      companyId
    });

    if (existingCommissions.length === 0) {
      await dbService.createMany(model.adminCommission, commissionData);
    }

    return res.success({
      message: 'Slab assigned to company successfully',
      data: { slabId, companyId }
    });
  } catch (error) {
    console.error(error);
    return res.internalServerError({ message: error.message });
  }
};

/**
 * Create Commission for Company Schema
 */
const createCompanyCommission = async (req, res) => {
  try {
    let permissions = req.permission || [];
    let hasPermission = permissions.some(
      (permission) =>
        permission.dataValues.permissionId === 27 &&
        permission.dataValues.write === true
    );

    if (req.user?.userType === USER_TYPES.SUPER_ADMIN) {
      hasPermission = true;
    }

    if (!hasPermission) {
      return res.failure({ message: `User doesn't have Permission!` });
    }

    const dataToCreate = { ...(req.body || {}) };
    const companyId = req.user?.companyId;

    if (!dataToCreate.schemaId || !dataToCreate.operatorId) {
      return res.failure({ message: 'Schema ID and Operator ID are required' });
    }

    // Verify schema exists
    const schema = await dbService.findOne(model.schema, {
      id: dataToCreate.schemaId,
      companyId
    });

    if (!schema) {
      return res.failure({ message: 'Schema not found' });
    }

    // Verify operator exists
    const operator = await dbService.findOne(model.operator, {
      id: dataToCreate.operatorId
    });

    if (!operator) {
      return res.failure({ message: 'Operator not found' });
    }

    dataToCreate.companyId = companyId;
    dataToCreate.operatorName = operator.operatorName;
    dataToCreate.operatorType = operator.operatorType;
    dataToCreate.roleType = schema.roleType;
    dataToCreate.roleName = schema.roleName;
    dataToCreate.commAmt = dataToCreate.commAmt || 0;
    dataToCreate.commType = dataToCreate.commType || 'com';
    dataToCreate.amtType = dataToCreate.amtType || 'fix';
    dataToCreate.isActive = true;
    dataToCreate.addedBy = req.user.id;

    // Check if commission already exists
    const existingCommission = await dbService.findOne(model.companyCommission, {
      schemaId: dataToCreate.schemaId,
      operatorId: dataToCreate.operatorId,
      roleType: dataToCreate.roleType,
      commType: dataToCreate.commType,
      assignedToUserId: dataToCreate.assignedToUserId || null
    });

    if (existingCommission) {
      // Update existing
      const updated = await dbService.update(
        model.companyCommission,
        { id: existingCommission.id },
        {
          ...dataToCreate,
          updatedBy: req.user.id
        }
      );
      return res.success({
        message: 'Commission updated successfully',
        data: updated[0]
      });
    }

    const created = await dbService.createOne(model.companyCommission, dataToCreate);

    return res.success({
      message: 'Commission created successfully',
      data: created
    });
  } catch (error) {
    console.error(error);
    if (error.name === 'SequelizeUniqueConstraintError') {
      return res.validationError({ message: error.errors[0].message });
    } else {
      return res.internalServerError({ message: error.message });
    }
  }
};

/**
 * Get Commissions by Schema
 */
const getCommissionsBySchema = async (req, res) => {
  try {
    let permissions = req.permission || [];
    let hasPermission = permissions.some(
      (permission) =>
        permission.dataValues.permissionId === 27 &&
        permission.dataValues.read === true
    );

    if (req.user?.userType === USER_TYPES.SUPER_ADMIN) {
      hasPermission = true;
    }

    if (!hasPermission) {
      return res.failure({ message: `User doesn't have Permission!` });
    }

    const { schemaId, roleType } = req.query;
    const companyId = req.user?.companyId;

    if (!schemaId) {
      return res.failure({ message: 'Schema ID is required' });
    }

    let query = { schemaId };
    if (companyId && req.user?.userType !== USER_TYPES.SUPER_ADMIN) {
      query.companyId = companyId;
    }

    if (roleType) {
      query.roleType = roleType;
    }

    // Determine which commission table to query based on roleType
    let commissionModel;
    if (roleType === 3) {
      commissionModel = model.masterDistributorCommission;
    } else if (roleType === 4) {
      commissionModel = model.distributorCommission;
    } else if (roleType === 5) {
      commissionModel = model.retailerCommission;
    } else {
      commissionModel = model.companyCommission;
    }

    const commissions = await dbService.findAll(commissionModel, query, {
      include: [
        { model: model.operator, as: 'operator' },
        { model: model.schema, as: 'schema' }
      ],
      order: [['id', 'ASC']]
    });

    return res.success({
      message: 'Commissions retrieved successfully',
      data: commissions
    });
  } catch (error) {
    console.error(error);
    return res.internalServerError({ message: error.message });
  }
};

/**
 * Get User Commissions
 */
const getUserCommissions = async (req, res) => {
  try {
    let permissions = req.permission || [];
    let hasPermission = permissions.some(
      (permission) =>
        permission.dataValues.permissionId === 27 &&
        permission.dataValues.read === true
    );

    if (req.user?.userType === USER_TYPES.SUPER_ADMIN) {
      hasPermission = true;
    }

    if (!hasPermission) {
      return res.failure({ message: `User doesn't have Permission!` });
    }

    const userId = req.params.userId;
    const companyId = req.user?.companyId;

    // Get user details
    const user = await dbService.findOne(model.user, {
      id: userId,
      companyId
    });

    if (!user) {
      return res.failure({ message: 'User not found' });
    }

    // Get user's schema
    const schema = await dbService.findOne(model.schema, {
      id: user.schemaId
    });

    if (!schema) {
      return res.success({
        message: 'User has no schema assigned',
        data: []
      });
    }

    // Get commissions based on user role
    let commissions = [];
    if (user.userRole === USER_TYPES.MASTER_DISTRIBUTOR) {
      commissions = await dbService.findAll(model.masterDistributorCommission, {
        schemaId: schema.id,
        masterDistributorId: userId
      }, {
        include: [{ model: model.operator, as: 'operator' }]
      });
    } else if (user.userRole === USER_TYPES.DISTRIBUTOR) {
      commissions = await dbService.findAll(model.distributorCommission, {
        schemaId: schema.id,
        distributorId: userId
      }, {
        include: [{ model: model.operator, as: 'operator' }]
      });
    } else if (user.userRole === USER_TYPES.RETAILER) {
      commissions = await dbService.findAll(model.retailerCommission, {
        schemaId: schema.id,
        retailerId: userId
      }, {
        include: [{ model: model.operator, as: 'operator' }]
      });
    } else {
      commissions = await dbService.findAll(model.companyCommission, {
        schemaId: schema.id,
        assignedToUserId: userId
      }, {
        include: [{ model: model.operator, as: 'operator' }]
      });
    }

    return res.success({
      message: 'User commissions retrieved successfully',
      data: {
        user: {
          id: user.id,
          name: user.name,
          userRole: user.userRole
        },
        schema: {
          id: schema.id,
          schemaName: schema.schemaName,
          schemaType: schema.schemaType
        },
        commissions
      }
    });
  } catch (error) {
    console.error(error);
    return res.internalServerError({ message: error.message });
  }
};

module.exports = {
  createSchema,
  updateSchema,
  getSchemaById,
  getAllSchemas,
  deleteSchema,
  assignSchemaToUser,
  assignSlabToCompany,
  createCompanyCommission,
  getCommissionsBySchema,
  getUserCommissions,
  autoGenerateDefaultSchemas
};




