const model = require('../../../models');
const dbService = require('../../../utils/dbService');
const { Op } = require('sequelize');
const { where, cast, col } = require('sequelize');
const imageService = require('../../../services/imageService');
const { uploadImageToS3, deleteImageFromS3, getImageUrl } = imageService;
const key = Buffer.from(process.env.AES_KEY, 'hex');
const { decrypt, doubleEncrypt } = require('../../../utils/doubleCheckUp');
const { generateOnboardingToken } = require('../../../utils/onboardingToken');
const { generateUniqueReferCode } = require('../../../utils/generateUniqueReferCode');
const { sendWelcomeEmail } = require('../../../services/emailService');
const { autoGenerateDefaultSchemas } = require('./companySchemaController');
const googleMap = require('../../../services/googleMap');
const postalPincode = require('../../../services/postalPincode');
const mapplesMap = require('../../../services/mapplesMap');

// Helper function to check IP address
const checkDomainIP = async (domain) => {
  const dns = require('dns').promises;
  
  // Get whitelisted IPs from environment variable
  const companyCheckIp = process.env.COMPANY_CHECK_IP;
  
  if (!companyCheckIp) {
    throw new Error('COMPANY_CHECK_IP environment variable is not configured');
  }

  // Parse the IP array from environment variable
  const whitelistedIPs = companyCheckIp
    .replace(/[\[\]]/g, '') // Remove brackets
    .split(',')
    .map(ip => ip.trim())
    .filter(ip => ip.length > 0);

  if (whitelistedIPs.length === 0) {
    throw new Error('No whitelisted IPs configured');
  }

  // Resolve domain to IPv4 addresses
  const resolvedIPs = await dns.resolve4(domain);
  
  console.log(`Domain ${domain} resolved to IPs: ${resolvedIPs.join(', ')}`);
  console.log(`Whitelisted IPs: ${whitelistedIPs.join(', ')}`);
  
  // Check if any resolved IP matches whitelisted IPs
  const matchedIPs = resolvedIPs.filter(ip => whitelistedIPs.includes(ip));
  
  if (matchedIPs.length === 0) {
    // Additional check: Try to find IPs in the same network range (first 3 octets match)
    const networkMatches = resolvedIPs.filter(resolvedIP => {
      const resolvedParts = resolvedIP.split('.');
      return whitelistedIPs.some(whitelistedIP => {
        const whitelistedParts = whitelistedIP.split('.');
        // Check if first 3 octets match (same network)
        return resolvedParts[0] === whitelistedParts[0] && 
               resolvedParts[1] === whitelistedParts[1] && 
               resolvedParts[2] === whitelistedParts[2];
      });
    });

    if (networkMatches.length > 0) {
      console.log(`Network match found but exact IP mismatch. Resolved: ${networkMatches.join(', ')}`);
      throw new Error(`Domain ${domain} resolves to IPs in the same network but not exact match. Resolved IPs: ${resolvedIPs.join(', ')}. Whitelisted IPs: ${whitelistedIPs.join(', ')}. Please update your DNS records or whitelist configuration.`);
    }
    
    throw new Error(`Domain ${domain} does not resolve to any whitelisted IP. Resolved IPs: ${resolvedIPs.join(', ')}. Whitelisted IPs: ${whitelistedIPs.join(', ')}`);
  }

  return {
    success: true,
    resolvedIPs,
    matchedIPs,
    whitelistedIPs
  };
};

const createCompany = async (req, res) => {
  try {
    let data = req.body;
    
    // Validate required fields (quick synchronous validation)
    const requiredFields = {
      BussinessEntity: 'Business entity is required',
      MobileNo: 'Mobile number is required',
      PanNumber: 'PAN number is required',
      PanName: 'PAN name is required',
      email: 'Email is required',
      address: 'Address is required',
      city: 'City is required',
      state: 'State is required',
      companyName: 'Company name is required',
      postalCode: 'Postal code is required',
      customDomain: 'Custom domain is required',
      Remarks: 'Remarks are required',
      verificationToken: 'Verification token is required. Please verify your IP first.'
    };

    for (const [field, message] of Object.entries(requiredFields)) {
      if (!data[field]) {
        return res.failure({ message });
      }
    }

    // Check if profileImage is provided either as S3 key or as file upload
    if(!data.profileImage && !req.file) {
      return res.failure({
        message: 'Profile image is required. Please provide either profileImage (S3 key) or upload a file.'
      });
    }

    // OPTIMIZATION: Validate token and run all duplicate checks in parallel
    const validateToken = async () => {
      try {
        const decodedToken = Buffer.from(data.verificationToken, 'base64').toString('utf-8');
        const encryptedToken = JSON.parse(decodedToken);
        const decryptedToken = decrypt(encryptedToken, key);
        
        if (!decryptedToken) {
          throw new Error('Invalid token format');
        }

        const tokenData = JSON.parse(decryptedToken);
        const tokenAge = Date.now() - tokenData.timestamp;
        const TOKEN_VALIDITY = 60 * 60 * 1000;
        
        if (tokenAge > TOKEN_VALIDITY) {
          throw new Error('Verification token has expired. Please verify your IP again.');
        }

        if (!tokenData.verified) {
          throw new Error('Invalid verification token');
        }

        if (tokenData.domain !== data.customDomain) {
          throw new Error('Domain mismatch. Verification token is for a different domain.');
        }

        return null; // Success
      } catch (tokenError) {
        throw tokenError;
      }
    };

    // OPTIMIZATION: Run all duplicate checks in parallel
    const [
      tokenError,
      existingPhone,
      existingEmail,
      existingDomain,
      existingCompany,
      existingPanCompany,
      existingPan
    ] = await Promise.all([
      validateToken().catch(err => err),
      dbService.findOne(model.user, { mobileNo: data.MobileNo, isDeleted: false }),
      dbService.findOne(model.user, { email: data.email, isDeleted: false }),
      dbService.findOne(model.company, { customDomain: data.customDomain, isDeleted: false }),
      dbService.findOne(model.company, { companyName: data.companyName, isDeleted: false }),
      dbService.findOne(model.company, { companyPan: data.PanNumber, isDeleted: false }),
      dbService.findOne(model.ekycHub, { identityNumber1: data.PanNumber, identityType: 'PAN' })
    ]);

    // Check token validation result
    if (tokenError instanceof Error) {
      return res.failure({
        message: tokenError.message || 'Invalid verification token. Please verify your IP again.'
      });
    }

    // Check duplicates (parallel results)
    if (existingPhone) {
      return res.failure({
        message: 'Phone number already exists',
        data: { mobileNo: data.MobileNo }
      });
    }

    if (existingEmail) {
      return res.failure({
        message: 'Email already exists',
        data: { email: data.email }
      });
    }

    if (existingDomain) {
      return res.failure({
        message: 'Domain name already exists',
        data: { customDomain: data.customDomain }
      });
    }

    if (existingCompany) {
      return res.failure({
        message: 'Company name already exists',
        data: { companyName: data.companyName }
      });
    }

    if (existingPanCompany) {
      return res.failure({
        message: 'PAN number already exists',
        data: { panNumber: data.PanNumber }
      });
    }

    // OPTIMIZED: Additional check for encrypted PAN duplicates (backward compatibility)
    // Only runs if direct query found nothing - handles cases where PAN might be stored encrypted
    // This is optimized to skip if there are too many companies (for performance)
    try {
      // Count companies first - if too many, skip encrypted check (performance optimization)
      const companyCount = await dbService.count(model.company, { isDeleted: false });
      
      // Only check encrypted PANs if we have reasonable number of companies (< 500)
      // Direct query should catch most duplicates anyway
      if (companyCount > 0 && companyCount < 500) {
        const allCompaniesWithPan = await dbService.findAll(
          model.company,
          { isDeleted: false },
          { attributes: ['id', 'companyPan'] }
        );

        if (allCompaniesWithPan && allCompaniesWithPan.length > 0) {
          const panToCheck = data.PanNumber.toLowerCase().trim();
          
          // Process in parallel chunks for better performance
          const chunkSize = 50;
          for (let i = 0; i < allCompaniesWithPan.length; i += chunkSize) {
            const chunk = allCompaniesWithPan.slice(i, i + chunkSize);
            
            for (const company of chunk) {
              // Skip if companyPan is plain text (already checked by direct query above)
              if (typeof company.companyPan === 'string' && 
                  !company.companyPan.includes('{') && 
                  !company.companyPan.includes('encrypted')) {
                continue;
              }
              
              let decryptedPan = null;
              try {
                // Try to parse as JSON (encrypted format)
                const panData = typeof company.companyPan === 'string' 
                  ? JSON.parse(company.companyPan) 
                  : company.companyPan;
                
                if (panData && panData.encrypted) {
                  // It's encrypted, decrypt it
                  decryptedPan = decrypt(panData, key);
                  
                  // Compare with input PAN (case-insensitive)
                  if (decryptedPan && decryptedPan.toLowerCase().trim() === panToCheck) {
                    return res.failure({
                      message: 'PAN number already exists',
                      data: { panNumber: data.PanNumber }
                    });
                  }
                }
              } catch (e) {
                // If parsing/decryption fails, skip this record
                continue;
              }
            }
          }
        }
      }
    } catch (panCheckError) {
      console.error('Error checking duplicate encrypted PAN:', panCheckError);
      // Don't fail the entire request if PAN check fails, but log it
      // The direct query above should catch most cases
    }

    // PAN verification check
    let panNameFromAPI = null;
    if (!existingPan) {
      return res.failure({
        message: 'PAN not found in verification records. Please fetch PAN verification first.',
        data: { panNumber: data.PanNumber }
      });
    }

    // Decrypt PAN verification result
    let panVerificationResult = null;
    try {
      const encryptedData = JSON.parse(existingPan.response);
      if (encryptedData && encryptedData.encrypted) {
        const decryptedResponse = decrypt(encryptedData, key);
        panVerificationResult = decryptedResponse ? JSON.parse(decryptedResponse) : encryptedData;
      } else {
        panVerificationResult = JSON.parse(existingPan.response);
      }
    } catch (e) {
      panVerificationResult = existingPan.response;
    }

    if (!panVerificationResult || panVerificationResult.status !== 'Success') {
      return res.failure({
        message: 'PAN verification failed. Please fetch PAN verification first.',
        data: {
          panNumber: data.PanNumber,
          status: panVerificationResult?.status || 'Failed'
        }
      });
    }

    panNameFromAPI = panVerificationResult.registered_name || panVerificationResult.data?.name || panVerificationResult.name;
    if (panNameFromAPI && panNameFromAPI.toLowerCase().trim() !== data.PanName.toLowerCase().trim()) {
      return res.failure({
        message: 'PAN name mismatch. Please verify your PAN name.',
        data: { providedPanName: data.PanName }
      });
    }

    // Prepare company data
    let profileImageKey = data.profileImage;
    const companyData = {
      companyName: data.companyName,
      companyPan: data.PanNumber,
      BussinessEntity: data.BussinessEntity,
      fullAddress: data.address,
      city: data.city,
      state: data.state,
      postalCode: data.postalCode,
      customDomain: data.customDomain,
      remark: data.Remarks,
      companyGst: data.companyGst,
      isActive: true
    };

    // OPTIMIZATION: Generate refer code in parallel with company creation
    const [company, referCode] = await Promise.all([
      dbService.createOne(model.company, companyData),
      generateUniqueReferCode(data.companyName)
    ]);

    const userData = {
      mobileNo: data.MobileNo,
      email: data.email,
      profileImage: profileImageKey,
      userRole: 2,
      companyId: company.id,
      userType: 1,
      name: panNameFromAPI || data.PanName,
      fullAddress: data.address,
      city: data.city,
      state: data.state,
      zipcode: data.postalCode,
      referCode: referCode,
      isActive: true,
      companyName: data.companyName,
    };

    let user = await dbService.createOne(model.user, userData);

    // OPTIMIZATION: Upload profile image in parallel with wallet creation
    const profileImageUpload = req.file && !data.profileImage
      ? (async () => {
          try {
            const uploadResult = await uploadImageToS3(
              req.file.buffer,
              req.file.originalname,
              'profile',
              company.id,
              null,
              user.id
            );
            profileImageKey = uploadResult.key;
            await dbService.update(model.user, { id: user.id }, { profileImage: profileImageKey });
            return uploadResult.key;
          } catch (uploadError) {
            console.error('Profile image upload error:', uploadError);
            throw uploadError;
          }
        })()
      : Promise.resolve(null);

    const walletData = {
      refId: user.id,
      companyId: company.id,
      mainWallet: 0,
      apesWallet: 0,
      roleType: 2
    };

    // Create wallet and upload image in parallel
    await Promise.all([
      dbService.createOne(model.wallet, walletData),
      profileImageUpload
    ]);

    // Reload user if image was uploaded
    if (req.file && !data.profileImage) {
      user = await dbService.findOne(model.user, { id: user.id });
    }

    // Generate onboarding token
    const onboardingExpiry = process.env.ON_BOARDING_EXPIRY || '6d';
    const tokenData = generateOnboardingToken({
      userId: user.id,
      name: user.name,
      companyId: company.id,
      userRole: user.userRole
    }, onboardingExpiry);

    // Save onboarding token
    await dbService.createOne(model.onboardingToken, {
      userId: user.id,
      companyId: company.id,
      token: tokenData.token,
      expiresAt: tokenData.expiresAt,
      isUsed: false
    });

    // OPTIMIZATION: Move email and schema creation to background (non-blocking)
    // Send response immediately, then handle async tasks
    const frontendUrl = process.env.FRONTEND_URL || 'https://app.gmaxepay.in';
    const onboardingLink = `${frontendUrl}/onboarding/${tokenData.token}`;
    const backendUrl = process.env.BASE_URL;
    const logoUrl = company.logo ? getImageUrl(company.logo) : `${backendUrl}/gmaxepay.png`;
    const iconUrl = `${backendUrl}/mailicons.png`;

    // Helper to get profile image URL
    const getProfileImageUrl = () => {
      if (!user.profileImage) return null;
      const cdnUrl = process.env.AWS_CDN_URL || 'https://assets.gmaxepay.in';
      let plainKey = user.profileImage;
      if (typeof plainKey === 'string' && !plainKey.startsWith('images/')) {
        try {
          const { decrypt } = require('../../../utils/encryption');
          plainKey = decrypt(plainKey);
        } catch (e) {
          // If decryption fails, use as is
        }
      }
      return plainKey ? `${cdnUrl}/${plainKey}` : null;
    };

    // Send response immediately
    const response = res.success({
      message: 'Company created successfully',
      data: {
        company: companyData,
        user: {
          id: user.id,
          userId: user.userId,
          mobileNo: user.mobileNo,
          email: user.email,
          referCode: user.referCode,
          profileImageUrl: getProfileImageUrl()
        }
      }
    });

    // OPTIMIZATION: Run async tasks in background (don't wait for them)
    setImmediate(async () => {
      try {
        // Send welcome email (non-blocking)
        await sendWelcomeEmail({
          to: user.email,
          userName: user.name,
          onboardingLink: onboardingLink,
          logoUrl: logoUrl,
          iconUrl: iconUrl,
          expiryTime: tokenData.expiryDisplay
        });
        console.log('Welcome email sent successfully to:', user.email);
      } catch (emailError) {
        console.error('Failed to send welcome email:', emailError);
      }

      try {
        // Create default schemas and slab (non-blocking)
        await assignBasicSlabToCompany(company.id, user.id);
        await Promise.all([
          autoGenerateDefaultSchemas(company.id, user.id, 3, 'MD'),
          autoGenerateDefaultSchemas(company.id, user.id, 4, 'DI'),
          autoGenerateDefaultSchemas(company.id, user.id, 5, 'RE')
        ]);
      } catch (schemaError) {
        console.error('Error creating default slab/schemas for company:', schemaError);
      }
    });

    return response;
  } catch (error) {
    console.error(error);
    return res.failure({ message: error.message });
  }
};

// Helper: assign default BASIC slab to a company (if slab exists)
const assignBasicSlabToCompany = async (companyId, addedByUserId) => {
  try {
    // Try to find a global BASIC slab (case-insensitive by name variants)
    let basicSlab =
      (await dbService.findOne(model.slab, { slabName: 'BASIC', slabScope: 'global' })) ||
      (await dbService.findOne(model.slab, { slabName: 'Basic', slabScope: 'global' })) ||
      (await dbService.findOne(model.slab, { slabName: 'basic', slabScope: 'global' }));

    if (!basicSlab) {
      // If no basic slab is defined, do nothing gracefully
      console.warn('No BASIC slab found to assign as default to company:', companyId);
      return;
    }

    // If adminCommission already exists for this slab+company, don't recreate
    const existing = await dbService.findAll(model.adminCommission, {
      slabId: basicSlab.id,
      companyId
    });
    if (existing && existing.length > 0) {
      return;
    }

    // Get all operators
    const operators = await dbService.findAll(
      model.operator,
      {},
      { select: ['id', 'operatorName', 'operatorType'] }
    );

    if (!operators || operators.length === 0) {
      return;
    }

    const commissionData = [];
    for (const op of operators) {
      // Commission row
      commissionData.push({
        schemaId: null,
        slabId: basicSlab.id,
        companyId,
        operatorId: op.id,
        operatorName: op.operatorName,
        operatorType: op.operatorType,
        commAmt: 0,
        commType: 'com',
        amtType: 'fix',
        isActive: true,
        addedBy: addedByUserId
      });
      // Surcharge row
      commissionData.push({
        schemaId: null,
        slabId: basicSlab.id,
        companyId,
        operatorId: op.id,
        operatorName: op.operatorName,
        operatorType: op.operatorType,
        commAmt: 0,
        commType: 'sur',
        amtType: 'fix',
        isActive: true,
        addedBy: addedByUserId
      });
    }

    await dbService.createMany(model.adminCommission, commissionData);
  } catch (error) {
    console.error('assignBasicSlabToCompany error:', error);
  }
};


const getPincodeByCity = async (req, res) => {
  try {
    const { city } = req.body;
    const user = await dbService.findOne(model.user, { id: req.user.id });
    if(!req.user.id){
      return res.failure({ message: 'User is not found required' });
    }
    
    if(!user) return res.failure({ message: 'User is not found' });
    
    if (!city) return res.failure({ message: 'City is required' });
    
    // Fetch pincode using postal pincode service
    const result = await postalPincode.getPincodeByCity(city);
    
    return res.success({ 
      message: 'Pincode fetched successfully', 
      data: result.data 
    });
  } catch (error) {
    console.error(error);
    return res.failure({ message: error.message });
  }
};

const getCityByPincode = async (req, res) => {
  try {
    const { pincode } = req.body;
    
    if (!pincode) return res.failure({ message: 'Pincode is required' });
    
    // Fetch city details using postal pincode service
    const result = await postalPincode.getCityByPincode(pincode);
    
    return res.success({ 
      message: 'City fetched successfully', 
      data: result.data
    });
  } catch (error) {
    console.error(error);
    return res.failure({ message: error.message });
  }
};


const getCompanyById = async (req, res) => {
  try {
    const { id } = req.params;
    if (!id) return res.failure({ message: 'Company ID is required' });

    const company = await dbService.findOne(model.company, { id });
    if (!company) return res.failure({ message: 'Company not found' });

    // Convert to JSON and add image URLs
    const companyData = company.toJSON();
    if (companyData.logo) {
      companyData.logoUrl = getImageUrl(companyData.logo);
    }
    if (companyData.favicon) {
      companyData.faviconUrl = getImageUrl(companyData.favicon);
    }

    return res.success({
      message: 'Company fetched successfully',
      data: companyData
    });
  } catch (error) {
    console.error(error);
    return res.failure({ message: error.message });
  }
};

const getAllCompanies = async (req, res) => {
  try {
    let dataToFind = req.body;
    let query = {};
    let options = {};

    if (dataToFind && dataToFind.query) {
      query = { ...query, ...dataToFind.query };
    }

    // Count-only response
    if (dataToFind?.isCountOnly) {
      const count = await dbService.count(model.company, query);
      if (!count) return res.recordNotFound();
      return res.success({ data: { totalRecords: count } });
    }

    if (dataToFind?.options !== undefined) {
      options = dataToFind.options;
    }

    if (dataToFind?.customSearch) {
      const keys = Object.keys(dataToFind.customSearch);
      const orConditions = [];

      keys.forEach((key) => {
        if (typeof dataToFind.customSearch[key] === 'number') {
          orConditions.push(
            where(cast(col(key), 'varchar'), {
              [Op.iLike]: `%${dataToFind.customSearch[key]}%`
            })
          );
        } else {
          orConditions.push({
            [key]: {
              [Op.iLike]: `%${dataToFind.customSearch[key]}%`
            }
          });
        }
      });

      if (orConditions.length > 0) {
        query[Op.or] = orConditions;
      }
    }

    const foundCompanies = await dbService.findAll(
      model.company,
      query,
      options
    );
    console.log('Found Companies:', foundCompanies);
    if (!foundCompanies || foundCompanies.length === 0) {
      return res.recordNotFound({ message: 'No companies found.' });
    }

    // Add image URLs to all companies
    const companiesWithUrls = foundCompanies.map(company => {
      const companyData = company.toJSON();
      if (companyData.logo) {
        companyData.logoUrl = getImageUrl(companyData.logo);
      }
      if (companyData.favicon) {
        companyData.faviconUrl = getImageUrl(companyData.favicon);
      }
      return companyData;
    });

    return res.success({
      message: 'Companies fetched successfully!',
      data: companiesWithUrls
    });
  } catch (error) {
    console.error(error);
    return res.failure({ message: error.message });
  }
};

const updateCompany = async (req, res) => {
  try {
    const { id } = req.params;
    let updateData = req.body;
    
    // Only allow specific fields to be updated
    const allowedFields = [
      'primaryColor',
      'secondaryColor',
      'singupPageDesign',
      'navigationBar',
      'supportPhoneNumbers',
      'customerSupportEmail',
      'companyName',
      'companyPan',
      'companyGst',
      'contactName',
      'contactEmail',
      'mobileNo',
      'BussinessEntity',
      'billingAddress',
      'shippingAddress',
      'modulesEnabled',
      'remark'
    ];
    
    // Filter only allowed fields
    const filteredData = {};
    allowedFields.forEach(field => {
      if (updateData[field] !== undefined) {
        filteredData[field] = updateData[field];
      }
    });
    
    // Handle modulesEnabled array parsing
    if (
      filteredData.modulesEnabled &&
      typeof filteredData.modulesEnabled === 'string'
    ) {
      filteredData.modulesEnabled = JSON.parse(
        filteredData.modulesEnabled.replace(/'/g, '"')
      );
    }
    
    // Handle supportPhoneNumbers array parsing
    if (
      filteredData.supportPhoneNumbers &&
      typeof filteredData.supportPhoneNumbers === 'string'
    ) {
      try {
        filteredData.supportPhoneNumbers = JSON.parse(filteredData.supportPhoneNumbers);
      } catch (e) {
        // If it's not JSON, split by comma
        filteredData.supportPhoneNumbers = filteredData.supportPhoneNumbers.split(',').map(s => s.trim());
      }
    }
    
    const company = await dbService.findOne(model.company, { id });
    if (!company) return res.failure({ message: 'Company not found' });
    
    const updated = await dbService.update(model.company, { id }, filteredData);
    
    // Fetch updated company to return with image URLs
    const updatedCompany = await dbService.findOne(model.company, { id });
    const companyData = updatedCompany.toJSON();
    if (companyData.logo) {
      companyData.logoUrl = getImageUrl(companyData.logo);
    }
    if (companyData.favicon) {
      companyData.faviconUrl = getImageUrl(companyData.favicon);
    }
    
    return res.success({
      message: 'Company updated successfully',
      data: companyData
    });
  } catch (error) {
    console.error(error);
    return res.failure({ message: error.message });
  }
};

const updateCompanyLogoAndFavicon = async (req, res) => {
  try {
    const { id } = req.params;
    const { type } = req.body; // 'logo' or 'favicon'
    
    if (!req.file) {
      return res.failure({ message: 'Image file is required' });
    }
    
    if (!type || !['logo', 'favicon'].includes(type)) {
      return res.failure({ message: 'Type must be either "logo" or "favicon"' });
    }
    
    const company = await dbService.findOne(model.company, { id });
    if (!company) return res.failure({ message: 'Company not found' });
    
    // Upload new image to S3
    const fileBuffer = req.file.buffer;
    const fileName = req.file.originalname;
    const uploadResult = await uploadImageToS3(
      fileBuffer,
      fileName,
      'company',
      id,
      type
    );
    
    // Delete old image from S3 if exists
    const oldImageKey = type === 'logo' ? company.logo : company.favicon;
    if (oldImageKey) {
      try {
        await deleteImageFromS3(oldImageKey);
      } catch (error) {
        console.error(`Error deleting old ${type}:`, error);
        // Continue even if deletion fails
      }
    }
    
    // Update company with new image
    const updateData = {
      [type]: uploadResult.key
    };
    
    const updated = await dbService.update(model.company, { id }, updateData);
    
    return res.success({
      message: `${type.charAt(0).toUpperCase() + type.slice(1)} updated successfully`,
      data: {
        ...updated.toJSON(),
        [`${type}Url`]: getImageUrl(uploadResult.key)
      }
    });
  } catch (error) {
    console.error(error);
    return res.failure({ message: error.message });
  }
};

const uploadProfileImage = async (req, res) => {
  try {
    if (!req.file) {
      return res.failure({ message: 'Image file is required' });
    }
    
    // Get user and company info for path pattern
    const { userId, companyId } = req.body;
    if (!userId || !companyId) {
      return res.failure({ message: 'userId and companyId are required' });
    }
    
    // Upload image to S3 with path pattern: images/{userId}/{companyId}/profile/
    const fileBuffer = req.file.buffer;
    const fileName = req.file.originalname;
    const uploadResult = await uploadImageToS3(
      fileBuffer,
      fileName,
      'profile',
      companyId, // companyId
      null, // subtype not needed
      userId // userId for path pattern: images/{userId}/{companyId}/profile/
    );
    
    // Return simple CDN URL (no secure proxy for profile images)
    const cdnUrl = process.env.AWS_CDN_URL || 'https://assets.gmaxepay.in';
    const profileImageUrl = `${cdnUrl}/${uploadResult.key}`;
    
    return res.success({
      message: 'Profile image uploaded successfully',
      data: {
        profileImage: uploadResult.key,
        profileImageUrl: profileImageUrl
      }
    });
  } catch (error) {
    console.error(error);
    return res.failure({ message: error.message });
  }
};

const deleteCompany = async (req, res) => {
  try {
    const { id } = req.params;

    const company = await dbService.findOne(model.company, { id });
    if (!company) return res.failure({ message: 'Company not found' });

    await dbService.destroy(model.company, { id });
    return res.success({
      message: 'Company deleted successfully',
      data: company
    });
  } catch (error) {
    console.error(error);
    return res.failure({ message: error.message });
  }
};


const getIpCheck = async (req, res)=>{
  try{
    const { domain } = req.body;
    
    if (!domain) {
      return res.failure({
        message: 'Domain is required'
      });
    }

    // Use the helper function to check IP
    try {
      const ipCheckResult = await checkDomainIP(domain);
      
      // Store IP info in database
      for (const ip of ipCheckResult.matchedIPs) {
        const existingIp = await dbService.findOne(model.ipInfo, {
          ipAddress: ip,
          ipType: 'WHITELIST'
        });

        if (!existingIp) {
          await dbService.createOne(model.ipInfo, {
            ipAddress: ip,
            ipType: 'WHITELIST'
          });
        }
      }

      // Generate verification token with encrypted data
      const tokenData = {
        domain: domain,
        timestamp: Date.now(),
        verified: true
      };

      // Encrypt the token
      const encryptedToken = doubleEncrypt(JSON.stringify(tokenData), key);

      // Convert encrypted token object to string for easier handling
      const verificationToken = Buffer.from(JSON.stringify(encryptedToken)).toString('base64');

      return res.success({
        message: 'IP verified successfully',
        data: {
          domain: domain,
          status: 'VERIFIED',
          verificationToken: verificationToken
        }
      });
    } catch (ipError) {
      return res.failure({
        message: 'IP verification failed - please check your IP',
        data: {
          domain: domain,
          status: 'FAILED'
        }
      });
    }
  } catch(error){
    console.error('IP check error:', error);
    return res.failure({
      message: error.message || 'IP verification failed'
    });
  }
}

const testCompletedAddress = async (req, res) => {
  try {
    const { ip, latitude, longitude } = req.body || {};
    if (!ip || !latitude || !longitude) {
      return res.failure({ message: 'IP, latitude and longitude are required' });
    }

    // Use Google Maps service for reverse geocoding
    const addressData = await googleMap.reverseGeocode(latitude, longitude);

    // Add IP and address field to response
    const response = {
      ...addressData,
      address: addressData.complete_address || addressData.formatted_address,
      ip: ip
    };

    return res.success({ 
      message: 'Complete address retrieved successfully', 
      data: response 
    });
  } catch (error) {
    console.error('Error in test completed address:', error);
    return res.failure({ 
      message: error.message || 'Failed to get complete address', 
      error: error.response?.data?.error_message || error.message 
    });
  }
}

const testMappplesMap = async (req, res) => {
  try {
    const { ip, latitude, longitude } = req.body;
    if (!ip || !latitude || !longitude) {
      return res.failure({ message: 'IP, latitude and longitude are required' });
    }

    // Use Mappls service for reverse geocoding
    const addressData = await mapplesMap.reverseGeocode(latitude, longitude);

    // Add IP and address field to response
    const response = {
      ...addressData,
      address: addressData.complete_address || addressData.formatted_address,
      ip: ip
    };

    return res.success({ 
      message: 'Complete address retrieved successfully from Mappls', 
      data: response 
    });
  } catch (error) {
    console.error('Error in test mappples modules:', error);
    return res.failure({ 
      message: error.message || 'Failed to get complete address from Mappls', 
      error: error.response?.data?.error_message || error.message 
    });
  }
}

// Deactivate an onboarding token by token string
const deactivateOnboarding = async (req, res) => {
  try {
    const { token } = req.params;
    if (!token) {
      return res.failure({ message: 'Token is required' });
    }

    const existing = await dbService.findOne(model.onboardingToken, {
      token: token
    });

    if (!existing) {
      return res.failure({ message: 'Onboarding token not found' });
    }

    if (existing.isUsed) {
      return res.failure({ message: 'Onboarding link is already deactivated' });
    }

    await dbService.update(
      model.onboardingToken,
      { id: existing.id },
      { isDeactivated: true, isUsed: true, usedAt: new Date() }
    );

    return res.success({ message: 'Onboarding link deactivated successfully' });
  } catch (error) {
    console.error('deactivateOnboarding error:', error);
    return res.failure({ message: error.message || 'Failed to deactivate onboarding link' });
  }
};

// Resend onboarding link for a company (generates a new token and emails it)
const resendOnboardingLink = async (req, res) => {
  try {
    const { companyid } = req.params;
    if (!companyid) {
      return res.failure({ message: 'Company ID is required' });
    }

    const company = await dbService.findOne(model.company, { id: companyid });
    if (!company) {
      return res.failure({ message: 'Company not found' });
    }

    // Find primary admin user for the company (role 2)
    const user = await dbService.findOne(model.user, {
      companyId: company.id,
      userRole: 2,
      isDeleted: false
    });

    console.log('user', user);

    if (!user) {
      return res.failure({ message: 'Primary user not found for this company' });
    }

    // Deactivate any existing active tokens for this user/company
    try {
      const existingActive = await dbService.findAll(
        model.onboardingToken,
        { userId: user.id, companyId: company.id, isUsed: false },
        {}
      );
      if (Array.isArray(existingActive)) {
        for (const t of existingActive) {
          await dbService.update(
            model.onboardingToken,
            { id: t.id },
            { isUsed: true, usedAt: new Date() }
          );
        }
      }
    } catch (ignore) {
      // best effort; continue even if listing/updating old tokens fails
    }

    // Generate a fresh token
    const onboardingExpiry = process.env.ON_BOARDING_EXPIRY || '6d';
    const tokenData = generateOnboardingToken({
      userId: user.id,
      name: user.name,
      companyId: company.id,
      userRole: user.userRole
    }, onboardingExpiry);

    // Save the new token
    await dbService.createOne(model.onboardingToken, {
      userId: user.id,
      companyId: company.id,
      token: tokenData.token,
      expiresAt: tokenData.expiresAt,
      isUsed: false
    });

    // Build URLs for email
    const frontendUrl = process.env.FRONTEND_URL || 'https://app.gmaxepay.in';
    const onboardingLink = `${frontendUrl}/onboarding/${tokenData.token}`;

    let logoUrl = company.logo ? getImageUrl(company.logo) : null;
    if (!logoUrl) {
      const backendUrl = process.env.BASE_URL;
      logoUrl = `${backendUrl}/gmaxepay.png`;
    }
    const backendUrl = process.env.BASE_URL;
    const iconUrl = `${backendUrl}/mailicons.png`;

    // Send email
    try {
      await sendWelcomeEmail({
        to: user.email,
        userName: user.name,
        onboardingLink: onboardingLink,
        logoUrl: logoUrl,
        iconUrl: iconUrl,
        expiryTime: tokenData.expiryDisplay
      });
    } catch (emailError) {
      console.error('Failed to send onboarding email:', emailError);
      // proceed; email failure shouldn't block token generation
    }

    return res.success({
      message: 'Onboarding link resent successfully',
      data: {
        onboardingLink,
        expiresAt: tokenData.expiresAt,
        expiryDisplay: tokenData.expiryDisplay
      }
    });
  } catch (error) {
    console.error('resendOnboardingLink error:', error);
    return res.failure({ message: error.message || 'Failed to resend onboarding link' });
  }
};


module.exports = {
  createCompany,
  getCompanyById,
  getAllCompanies,
  updateCompany,
  updateCompanyLogoAndFavicon,
  uploadProfileImage,
  deleteCompany,
  getPincodeByCity,
  getCityByPincode,
  getIpCheck,
  testCompletedAddress,
  testMappplesMap,
  deactivateOnboarding,
  resendOnboardingLink
};
