const { S3Client, PutObjectCommand, DeleteObjectCommand, GetObjectCommand } = require('@aws-sdk/client-s3');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// Initialize S3 Client
const s3Client = new S3Client({
  region: process.env.AWS_REGION || 'us-east-1',
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  }
});

const BUCKET_NAME = process.env.AWS_BUCKET || 'gmaxepay';
const AWS_CDN_URL = process.env.AWS_CDN_URL || 'https://cdn.gmaxepay.in';

/**
 * Get image URL pointing to backend server (proxy endpoint with CORS support)
 * @param {String} s3Key - S3 object key (already includes 'images/' prefix)
 * @returns {String} - Backend API URL for the image (with CORS headers)
 */
const getImageUrl = (s3Key) => {
  if (!s3Key) return null;
  // Use backend API proxy endpoint instead of CDN to avoid CORS issues
  // The proxy endpoint at /api/images/* has CORS headers configured
  const backendUrl = process.env.BASE_URL || process.env.API_URL || 'http://localhost:3000';
  return `${backendUrl}/api/images/${s3Key}`;
};

/**
 * Upload image to S3
 * @param {Buffer} fileBuffer - File buffer
 * @param {String} fileName - File name
 * @param {String} type - Image type (loginSlider, signature)
 * @param {String} companyId - Company ID
 * @param {String} subtype - For signature type (logo, stamp, signature)
 * @returns {Promise<Object>} - Returns S3 URL and key
 */
const uploadImageToS3 = async (fileBuffer, fileName, type, companyId, subtype = null) => {
  try {
    // Generate unique file name
    const timestamp = Date.now();
    const randomString = crypto.randomBytes(8).toString('hex');
    const ext = path.extname(fileName) || '.jpg';
    const sanitizedFileName = `${timestamp}_${randomString}${ext}`;
    
    // Construct S3 key based on type
    let s3Key;
    if (type === 'loginSlider') {
      s3Key = `images/${companyId||'default'}/loginSlider/${sanitizedFileName}`;
    } else if (type === 'signature' && subtype) {
      s3Key = `images/${companyId||'default'}/signature/${subtype}/${sanitizedFileName}`;
    } else if (type === 'company' && subtype) {
      s3Key = `images/company/${companyId||'default'}/${subtype}/${sanitizedFileName}`;
    } else if (type === 'profile' && subtype) {
      s3Key = `images/profile/${subtype}/${sanitizedFileName}`;
    } else if (type === 'shop') {
      s3Key = `images/${companyId||'default'}/shop/${sanitizedFileName}`;
    } else {
      s3Key = `images/${companyId||'default'}/other/${sanitizedFileName}`;
    }
    
    // Upload to S3
    const params = {
      Bucket: BUCKET_NAME,
      Key: s3Key,
      Body: fileBuffer,
      ContentType: 'image/jpeg' // Adjust based on your needs
    };
    
    await s3Client.send(new PutObjectCommand(params));
    
    // Return S3 key only, URL will be generated by backend
    return {
      url: s3Key, // Store only the key
      key: s3Key
    };
  } catch (error) {
    console.error('Error uploading image to S3:', error);
    throw error;
  }
};

/**
 * Delete image from S3
 * @param {String} s3Key - S3 object key
 * @returns {Promise<Boolean>}
 */
const deleteImageFromS3 = async (s3Key) => {
  try {
    const params = {
      Bucket: BUCKET_NAME,
      Key: s3Key
    };
    
    await s3Client.send(new DeleteObjectCommand(params));
    return true;
  } catch (error) {
    console.error('Error deleting image from S3:', error);
    throw error;
  }
};

/**
 * Get image from S3
 * @param {String} s3Key - S3 object key
 * @returns {Promise<Buffer>}
 */
const getImageFromS3 = async (s3Key) => {
  try {
    const params = {
      Bucket: BUCKET_NAME,
      Key: s3Key
    };
    
    const response = await s3Client.send(new GetObjectCommand(params));
    const chunks = [];
    
    for await (const chunk of response.Body) {
      chunks.push(chunk);
    }
    
    return Buffer.concat(chunks);
  } catch (error) {
    console.error('Error getting image from S3:', error);
    throw error;
  }
};

module.exports = {
  uploadImageToS3,
  deleteImageFromS3,
  getImageFromS3,
  getImageUrl,
  BUCKET_NAME
};

