const dbService = require('../../../utils/dbService');
const model = require('../../../models');
const ekycHub = require('../../../services/eKycHub');
const { generateTransactionID } = require('../../../utils/transactionID');

const panCardActions = async (req, res) => {
  try {
    const userId = req.user.id;
    const companyId = req.user.companyId;
    const { mobile_number,action} = req.body;

    // Get user details
    const user = await dbService.findOne(
      model.user,
      { id: userId },
      {
        attributes: ['id', 'mobileNo', 'companyId', 'name', 'email']
      }
    );

    if (!user) {
      return res.failure({ message: 'User not found' });
    }

    // Ensure companyId is available
    const finalCompanyId = companyId || user.companyId;
    if (!finalCompanyId) {
      return res.failure({ message: 'Company ID is required' });
    }

    // Get mobile number from request body or user
    const mobileNumber = mobile_number || user.mobileNo;
    if (!mobileNumber) {
      return res.failure({ message: 'Mobile number is required' });
    }

    // Fetch company to get company name for transaction ID generation
    const existingCompany = await dbService.findOne(
      model.company,
      { id: finalCompanyId }
    );

    if (!existingCompany) {
      return res.failure({ message: 'Company not found' });
    }

    // Validate action
    if (!action || (action !== 'new' && action !== 'correction')) {
      return res.failure({ message: 'Invalid action. Action must be either "new" or "correction"' });
    }

    // Generate unique transaction ID using company name (for internal tracking)
    const transactionId = generateTransactionID(existingCompany?.companyName);
    const mode = 'EKYC';
    
    // Call eKycHub service to get PAN redirection URL (service will generate orderid internally)
    let response;
    if (action === 'correction') {
      response = await ekycHub.panCardCorrection(mobileNumber, mode);
      console.log("response", response);
    } else if (action === 'new') {
      response = await ekycHub.panCardNew(mobileNumber, mode);
      console.log("response", response);
    }
    
    // Validate response exists
    if (!response) {
      return res.failure({ message: 'No response from PAN card service' });
    }
    
    // Get orderid from response (generated by service)
    const orderid = response.orderid || null;

    // Save request/response to database
    const panCardRequestData = {
      refId: userId,
      companyId: finalCompanyId,
      orderid: orderid,
      transactionId: transactionId,
      mobile_number: mobileNumber,
      redirect_url: response.redirect_url || null,
      status: response.status || 'Failed',
      type: action,
      request: JSON.stringify({
        mobile_number: mobileNumber,
        orderid: orderid
      }),
      response: JSON.stringify(response),
      addedBy: userId,
      updatedBy: userId
    };

    await dbService.createOne(model.panCardCrud, panCardRequestData);

    if (response.status === 'Success' && response.redirect_url) {
      return res.success({
        message: response.message || 'PAN redirection URL created successfully',
        data: {
          redirect_url: response.redirect_url,
          orderid: orderid
        }
      });
    } else {
      return res.failure({
        message: response.message || 'Failed to create PAN redirection URL',
        data: response
      });
    }
  } catch (error) {
    console.error('PAN redirection error:', error);
    return res.internalServerError({ message: error.message });
  }
};

module.exports = {
  panCardActions
};

